#!/bin/bash

echo "=== Website Blocker Extension Test Script ==="
echo "1. Open chrome://extensions/ in Developer Mode"
echo "2. Click 'Load unpacked' and select the website-blocker directory"
echo "3. Open the debug page at chrome-extension://<extension-id>/test/debug.html"
echo ""
echo "Test Cases:"
echo "1. Storage Operations"
echo "  - View initial storage (should be empty or have migrated sites)"
echo "  - Add example.com to storage"
echo "  - Verify storage contents updated"
echo "  - Clear storage and verify empty"
echo ""
echo "2. Rule Operations"
echo "  - View initial rules"
echo "  - Add example.com rule"
echo "  - Verify rule added"
echo "  - Remove all rules and verify empty"
echo ""
echo "3. Synchronization"
echo "  - Add site to storage"
echo "  - Verify both storage and rules updated"
echo "  - Remove site"
echo "  - Verify both storage and rules cleared"
echo ""
echo "4. Migration"
echo "  - Clear storage"
echo "  - Reload extension"
echo "  - Verify initial sites migrated correctly"
echo ""
echo "Press Enter after completing each test case..."
